project_id = "yfseeexwafzmezufwdxq"

[functions.send-evaluation]
verify_jwt = true

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-auto-webhook]
verify_jwt = true

[functions.send-telegram-message]
verify_jwt = true

[functions.send-telegram-media]
verify_jwt = true

[functions.send-auto-message]
verify_jwt = true

[functions.delete-telegram-message]
verify_jwt = true

[functions.telegram-check-online]
verify_jwt = true

[functions.update-contacts-online-status]
verify_jwt = true

[functions.waba-webhook]
verify_jwt = false

[functions.get-system-secrets]
verify_jwt = true

[functions.save-system-secrets]
verify_jwt = true

[functions.facebook-webhook]
verify_jwt = false

[functions.send-waba-message]
verify_jwt = true

[functions.send-facebook-message]
verify_jwt = true

[functions.create-tenant]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-all-users]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = true

[functions.process-invoice-payment]
verify_jwt = true

[functions.check-expired-subscriptions]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.test-gateway]
verify_jwt = true

[functions.send-invoice-notification]
verify_jwt = true